###############################################################################
# General Configuration
###############################################################################
version: 0.2.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2019

configuration: 
  - Release
  - Debug
platform: 
  - x64
  - x86
environment:
  matrix:
  - solution_name: Samples/IDE/VS/Samples.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%